# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2543b7d603ad5c3e0cadf2ffcbf0881bc791ea6af2c829d6d19bbc36feccc015ef496ed032d0df9ead590f8b9b270cd591f64201aa1aeee176f95a991999979e

test:
  secret_key_base: 93d2cf9de613d312049a6216c4937a1a19d3eda9d1e4a8556c3f29cc4903acf66479e173b357aca5a774d0d7ccb35ee0790b9dd64a8d1c72b904b7a1995134c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
